version: '3.7'

services:
  age:
    image: apache/age:latest
    container_name: age
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
